import { Palette } from "std-widgets.slint";

export component PageHeader {
    in property<string> title: "";
    height: 78px;

    Text {
        x: 24px;
        y: 10px;
        text: root.title;
        color: Palette.foreground;
        font-size: 34px;
        font-weight: 700;
    }

    Rectangle {
        x: 26px;
        y: 58px;
        width: 300px;
        height: 4px;
        border-radius: 2px;
        background: @linear-gradient(90deg, #8b7bf7 0%, #ffffff80 70%, transparent 100%);
    }
}
