import { Palette } from "std-widgets.slint";
import { PageHeader } from "components/page-header.slint";
import { SettingsPageData } from "settings-page-data.slint";
import { Sizing } from "sizing.slint";

component Field inherits Rectangle {
    in property<string> label: "";
    in property<string> value: "";
    height: Sizing.small * 110%;
    background: transparent;

    Text {
        x: Sizing.small * 50%;
        vertical-alignment: center;
        text: root.label;
        color: Palette.foreground.with-alpha(70%);
    }

    Text {
        x: Sizing.screen-width * 19%;
        vertical-alignment: center;
        text: root.value;
        color: Palette.foreground;
    }
}

component EditField inherits Rectangle {
    in property<string> label: "";
    in-out property<string> value: "";
    callback save(string);

    height: Sizing.small * 130%;
    background: transparent;

    Text {
        x: Sizing.small * 50%;
        vertical-alignment: center;
        text: root.label;
        color: Palette.foreground.with-alpha(70%);
    }

    Rectangle {
        x: Sizing.screen-width * 19%;
        y: (root.height - self.height) / 2;
        width: Sizing.screen-width * 33%;
        height: Sizing.small * 95%;
        border-radius: Sizing.small * 25%;
        background: Palette.foreground.with-alpha(7%);

        input := TextInput {
            x: Sizing.small * 25%;
            width: parent.width - Sizing.small * 50%;
            height: parent.height;
            vertical-alignment: center;
            text <=> root.value;
            color: Palette.foreground;
            single-line: true;
        }
    }

    Rectangle {
        x: Sizing.screen-width * 54%;
        y: (root.height - self.height) / 2;
        width: Sizing.screen-width * 9.5%;
        height: Sizing.small * 95%;
        border-radius: Sizing.small * 25%;
        background: Palette.accent-background.with-alpha(touch.has-hover ? 100% : 80%);

        Text {
            text: "保存";
            color: Palette.accent-foreground;
            horizontal-alignment: center;
            vertical-alignment: center;
        }

        touch := TouchArea {
            clicked => { root.save(root.value); }
        }
    }
}

export component SettingsPage {
    VerticalLayout {
        width: 100%;
        height: 100%;
        padding: 0px;
        spacing: 0px;

        PageHeader {
            title: "设置";
        }

        EditField {
            label: "服务器地址";
            value <=> SettingsPageData.server-ip;
            save(ip) => { SettingsPageData.save(ip); }
        }

        Field { label: "检测模型"; value: SettingsPageData.model; }
        Field { label: "视频源"; value: SettingsPageData.video; }
        Field { label: "判定线"; value: "在人数监控页标定"; }
        Field { label: "图传地址"; value: SettingsPageData.udp; }

        Text {
            x: Sizing.small * 50%;
            text: SettingsPageData.hint;
            color: Palette.accent-background;
        }
    }
}
